# Generated by Django 4.1.3 on 2022-12-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0002_keywords_priorityuser_scrapedata_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='word',
            new_name='name',
        ),
    ]
