# Generated by Django 4.1.3 on 2022-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0003_rename_word_keywords_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='mentioned_users',
            field=models.ManyToManyField(null=True, to='ScammerHuntCore.priorityuser'),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='reference_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
