# Generated by Django 4.1.3 on 2022-12-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0004_alter_scrapedata_mentioned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='scammer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ScammerHuntCore.scammer'),
        ),
    ]
