# Generated by Django 4.1.3 on 2022-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0008_remove_scrapedata_id_scrapedata_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='keywords',
            field=models.ManyToManyField(to='ScammerHuntCore.keywords'),
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='mentioned_users',
            field=models.ManyToManyField(related_name='data_mentioned_users', to='ScammerHuntCore.priorityuser'),
        ),
    ]
