# Generated by Django 4.1.3 on 2022-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0009_scrapedata_keywords_scrapedata_mentioned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='reference_link',
            field=models.TextField(default='', primary_key=True, serialize=False, unique=True),
        ),
    ]
