# Generated by Django 4.1.3 on 2022-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0010_alter_scrapedata_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='sentiment_score',
            field=models.IntegerField(default=0),
        ),
    ]
