# Generated by Django 4.1.3 on 2022-12-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0011_scrapedata_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='carrier',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='scammer',
            name='geocoder',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='scammer',
            name='timezone',
            field=models.CharField(default='', max_length=300),
        ),
    ]
