# Generated by Django 4.1.3 on 2022-12-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0014_alter_scrapedata_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='upi_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
