# Generated by Django 4.1.3 on 2022-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0015_scammer_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.CharField(default='', max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='scammer',
            name='scaupi_ids',
            field=models.ManyToManyField(to='ScammerHuntCore.upi'),
        ),
    ]
