# Generated by Django 4.1.3 on 2022-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScammerHuntCore', '0006_rename_user_name_priorityuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scammer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scrapedata',
            name='id',
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scammer',
            name='phone_number',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='mentioned_users',
            field=models.ManyToManyField(to='ScammerHuntCore.priorityuser'),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='reference_link',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='scrapedata',
            name='scammer',
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='scammer',
            field=models.ManyToManyField(to='ScammerHuntCore.scammer'),
        ),
    ]
